name: Run TAGameGiveaway Script
#test
on:
  schedule:
    - cron: "0 10 * * *" # Runs at 5 am Eastern (10 am UTC)
  workflow_dispatch: # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9" # Change if necessary

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright python-dotenv
        playwright install --with-deps

    - name: Verify script content
      run: cat TAGameGiveaway.py

    - name: Run TAGameGiveaway Script
      env:
        TAUSERNAME: ${{ secrets.TAUSERNAME }}
        TAPASSWORD: ${{ secrets.TAPASSWORD }}
      run: python TAGameGiveaway.py
